import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 12,
    paddingBottom: 30,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#CBD5E1",
  },
  loadingText: {
    color: "#475569",
    marginTop: 12,
    fontSize: 14,
    fontWeight: "bold",
  },
  searchSection: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    marginHorizontal: 12,
    marginTop: 12,
    borderRadius: 10,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: "#CBD5E1",
    height: 44,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    color: "#1E293B",
    fontSize: 14,
    fontWeight: "600",
  },
  typeFilterContainer: {
    marginVertical: 10,
    paddingLeft: 12,
  },
  typeFilterScroll: {
    paddingRight: 24,
    gap: 8,
  },
  typeFilterButton: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  typeFilterText: {
    fontSize: 11,
    fontWeight: "800",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  cardWrapper: {
    width: "48%",
    marginBottom: 12,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#CBD5E1",
  },
  number: {
    alignSelf: "flex-start",
    color: "#94A3B8",
    fontSize: 10,
    fontWeight: "800",
  },
  imageContainer: {
    width: 75,
    height: 75,
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 2,
  },
  image: {
    width: 110,
    height: 110,
    resizeMode: "contain",
  },
  name: {
    color: "#1E293B",
    fontSize: 15,
    fontWeight: "800",
    textTransform: "capitalize",
  },
  typeContainer: {
    flexDirection: "row",
    marginTop: 4,
  },
  typeBadge: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "700",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    textTransform: "uppercase",
  },

  // DESIGN DO PORTÁTIL INTERNO DA POKÉDEX REVISADO
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  gbaConsoleContainer: {
    backgroundColor: "#CC0000", // Trocado para o Vermelho Oficial da Pokédex!
    borderRadius: 20,
    width: "100%",
    maxWidth: 360,
    height: "72%", // Altura reduzida com precisão para ficar bem ajustado e proporcional
    padding: 14,
    borderWidth: 4,
    borderColor: "#530000", // Relevo escuro combinando com o plástico da Pokédex
    borderBottomWidth: 10, 
    justifyContent: "space-between",
  },
  gbaScreenBorder: {
    flex: 1,
    backgroundColor: "#1A1A1A", 
    borderRadius: 10,
    padding: 10,
    borderWidth: 3,
    borderColor: "#2B2B2B",
  },
  gbaLcdHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#333",
    paddingBottom: 6,
    marginBottom: 8,
  },
  gbaHeaderText: {
    color: "#8F8F8F",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },
  gbaCloseCross: {
    backgroundColor: "#2B2B2B",
    borderRadius: 4,
    padding: 2,
    borderWidth: 1,
    borderColor: "#444",
  },
  gbaMainDisplay: {
    flex: 1,
    backgroundColor: "#F0F3F1", 
    borderRadius: 6,
    padding: 10,
    borderWidth: 2,
    borderColor: "#000000",
  },
  gbaTopRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 10,
    alignItems: "center",
  },
  gbaSpriteBox: {
    backgroundColor: "#DCE5E1",
    borderWidth: 2,
    borderColor: "#7F8C8D",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    width: 115, 
    height: 115,
    overflow: "hidden",
  },
  gbaImage: {
    width: "100%", // Preenche todo o box interno horizontalmente
    height: "100%", // Preenche todo o box interno verticalmente
    resizeMode: "contain", // Garante que a imagem exploda de tamanho mantendo a proporção pixel do sprite
  },
  gbaProfileData: {
    flex: 1,
    justifyContent: "center",
  },
  gbaIndexText: {
    fontSize: 12,
    fontWeight: "900",
    color: "#530000",
    marginBottom: 1,
  },
  gbaPokemonName: {
    fontSize: 20,
    fontWeight: "900",
    color: "#111111",
    marginBottom: 2,
  },
  gbaLabelMini: {
    fontSize: 9,
    fontWeight: "800",
    color: "#7F8C8D",
    marginTop: 2,
  },
  gbaValueMini: {
    fontSize: 11,
    fontWeight: "700",
    color: "#222222",
  },
  gbaTypeRow: {
    flexDirection: "row",
    gap: 4,
    marginTop: 2,
  },
  gbaTypeLabel: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "900",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    textAlign: "center",
  },
  gbaStatsContainer: {
    backgroundColor: "#E2ECE9",
    borderRadius: 6,
    padding: 8,
    borderWidth: 1.5,
    borderColor: "#95A5A6",
    marginBottom: 8,
  },
  gbaStatsTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#2C3E50",
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#BDC3C7",
    paddingBottom: 2,
  },
  gbaStatRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  gbaStatNameLabel: {
    width: 55,
    fontSize: 10,
    fontWeight: "800",
    color: "#4A5568",
  },
  gbaStatValueNum: {
    width: 24,
    fontSize: 10,
    fontWeight: "900",
    color: "#111111",
    textAlign: "right",
    marginRight: 6,
  },
  gbaBarWrapper: {
    flex: 1,
    height: 7,
    backgroundColor: "#CBD5E1",
    borderRadius: 2,
    overflow: "hidden",
  },
  gbaBarFill: {
    height: "100%",
    borderRadius: 2,
  },
  gbaMovesContainer: {
    backgroundColor: "#E2ECE9",
    borderRadius: 6,
    padding: 8,
    borderWidth: 1.5,
    borderColor: "#95A5A6",
    marginBottom: 4,
  },
  gbaMovesTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#2C3E50",
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#BDC3C7",
    paddingBottom: 2,
  },
  gbaMovesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 4,
  },
  gbaMoveCard: {
    width: "49%",
    backgroundColor: "#D6E4E0",
    borderRadius: 4,
    paddingHorizontal: 4,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    borderWidth: 1,
    borderColor: "#B5C7C2",
  },
  gbaMoveText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#2D3748",
  },
  gbaControllerFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
  },
  gbaBButtonAction: {
    paddingVertical: 4,
    paddingRight: 10,
  },
  gbaButtonHint: {
    color: "#FFD2D2",
    fontSize: 10,
    fontWeight: "bold",
  },
  gbaLogoContainer: {
    alignItems: "trailing",
  },
  gbaLogoText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
    fontStyle: "italic",
  },
  gbaLogoSub: {
    color: "#FFCC00",
    fontSize: 9,
    fontWeight: "900",
    fontStyle: "italic",
    textAlign: "right",
    marginTop: -2,
  },
});